spring:
  application:
    name: role-service
  profiles:
   active:
    - db
    - swagger
    - actuator
  config:
    import: optional:configserver:http://127.0.0.1:8888

eureka:
  instance:
    prefer-ip-address: true