server:
  port: 8002

springdoc:
  title: Member API Document
  version: 1.0.0
  swagger-ui:
    path: /members/api-docs
   
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/member;
      username: sa
      password: 
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8100/eureka/
    