server:
  port: 8001

springdoc:
  title: Role API Document
  version: 1.0.0
  swagger-ui:
    path: /roles/api-docs

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/role;
      username: sa
      password: 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8100/eureka/
