server:
  port: 8888
spring:
  application:
    name: config-service
  profiles: 
    active: native

---
# GIT
spring:
  config:
    activate:
      on-profile: git # Profile명 지정
  cloud:
    config:
      server:
        git: 
          uri: https://github.com/KIM-JONG-YOUNG/spring-cloud
          search-paths: spring-config-server/config                # Folder 명
          default-label: master                                                    # Branch 정보
          delete-untracked-branches: true                                # Remote Repository만 사용
---
# Local File
spring:
  config:
    activate:
      on-profile: native # Profile명 지정
  cloud:
    config:
      server:
        native:
          search-locations:  file:./config
