server:
  port: 8888
spring:
  application:
    name: config-service
  profiles: #그냥 로컬 파일
    active: git

---
# Local GIT
spring:
  config:
    activate:
      on-profile: git
  cloud:
    config:
      server:
        git: #local git
          uri: https://github.com/KIM-JONG-YOUNG/spring-cloud
          search-paths: config # Folder 명
          default-label: master # Branch 정보
          delete-untracked-branches: true # Remote Repository만 사용
---
# Local File
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations:  file:///D:/Projects/Law/working/workspace/spring-cloud/config
