spring:
  application:
    name: gateway-service
  profiles:
    active:
    - actuator
  config:
    import: optional:configserver:http://127.0.0.1:8888
  main:
    web-application-type: reactive

#---
#server:
#  port: 8000
#
#spring:
#  cloud:
#    gateway:
#      default-filters:
#        - AddRequestHeader=Authorization-Token, prop-test
#        - name: TokenCheckFilter
#          args:
#            permitAll: method,url
#          
#      routes:
#        - id: role-service
#          uri: http://localhost:8001
#          predicates:
#            - Path=/roles/**
#        - id: member-service
#          uri: http://localhost:8002
#          predicates:
#            - Path=/members/**
#            
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8100/eureka/
    